# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vital_crm
spring.datasource.username=root
spring.datasource.password=root

server.servlet.context-path=/api/v1

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a4fcd1001@smtp-brevo.com
spring.mail.password=xsmtpsib-ea9debbb9dbc2dde5d838269a349966270bf6e32e615c1427b8a3671c163098e-1rB8ZgFc5c8I2DoP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=yosrii.jemaiii@gmail.com 

# JWT Configuration
jwt.secret=vG9K7+W0K8mYkKJ9W6X+vM/2p3zQYbL1+3Fk2u0sPvA=
jwt.expiration=18000000

# Python API URL
python.api.url=http://localhost:8000

